DELETE
FROM CATEGORY;
/*ALTER TABLE CATEGORY AUTO_INCREMENT = 1;*/
SET
@n_category = 10;

INSERT INTO CATEGORY (name, img, CREATION_DATE, UPDATE_DATE)
SELECT 'Cash',
       'cash-outline',
       CURRENT_TIMESTAMP,
       CURRENT_TIMESTAMP WHERE (SELECT COUNT(*) FROM CATEGORY) < @n_category;

INSERT INTO CATEGORY (name, img, CREATION_DATE, UPDATE_DATE)
SELECT 'Credit Card',
       'card-outline',
       CURRENT_TIMESTAMP,
       CURRENT_TIMESTAMP WHERE (SELECT COUNT(*) FROM CATEGORY) < @n_category;

INSERT INTO CATEGORY (name, img, CREATION_DATE, UPDATE_DATE)
SELECT 'Debit Card',
       'card-outline',
       CURRENT_TIMESTAMP,
       CURRENT_TIMESTAMP WHERE (SELECT COUNT(*) FROM CATEGORY) < @n_category;

INSERT INTO CATEGORY (name, img, CREATION_DATE, UPDATE_DATE)
SELECT 'Recurrence',
       'alarm-outline',
       CURRENT_TIMESTAMP,
       CURRENT_TIMESTAMP WHERE (SELECT COUNT(*) FROM CATEGORY) < @n_category;

INSERT INTO CATEGORY (name, img, CREATION_DATE, UPDATE_DATE)
SELECT 'Bank Account',
       'wallet-outline',
       CURRENT_TIMESTAMP,
       CURRENT_TIMESTAMP WHERE (SELECT COUNT(*) FROM CATEGORY) < @n_category;

INSERT INTO CATEGORY (name, img, CREATION_DATE, UPDATE_DATE)
SELECT 'Save',
       'lock-closed-outline',
       CURRENT_TIMESTAMP,
       CURRENT_TIMESTAMP WHERE (SELECT COUNT(*) FROM CATEGORY) < @n_category;

INSERT INTO CATEGORY (name, img, CREATION_DATE, UPDATE_DATE)
SELECT 'Coupon', 'ticket-outline', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP WHERE (SELECT COUNT(*) FROM CATEGORY) < @n_category;

INSERT INTO CATEGORY (name, img, CREATION_DATE, UPDATE_DATE)
SELECT 'Check', 'id-card-outline', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP WHERE (SELECT COUNT(*) FROM CATEGORY) < @n_category;

INSERT INTO CATEGORY (name, img, CREATION_DATE, UPDATE_DATE)
SELECT 'Investments',
       'bar-chart-outline',
       CURRENT_TIMESTAMP,
       CURRENT_TIMESTAMP WHERE (SELECT COUNT(*) FROM CATEGORY) < @n_category;

INSERT INTO CATEGORY (name, img, CREATION_DATE, UPDATE_DATE)
SELECT 'Others', 'cube-outline', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP WHERE (SELECT COUNT(*) FROM CATEGORY) < @n_category;